name: build-and-test

on:
  workflow_dispatch:

jobs:
  test-gpu:
    runs-on: cern-nextgen-gpu
    container: registry.cern.ch/docker.io/rochaporto/gpu_burn
    steps:
      - name: nvidia-smi
        run: |
          nvidia-smi
      - name: install
        run: |
          apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys A4B469963BF863CC
          apt-get -y update
          DEBIAN_FRONTEND=noninteractive apt-get -y install cmake
      - name: configure
        run: |
          pwd
          ls -la .
          cmake -B build
      - name: build
        run: |
          cmake --build build
      - name: test
        run: |
          ctest --test-dir build
