name: build-and-test

on:
  workflow_dispatch:

jobs:
  test-gpu:
    runs-on: cern-nextgen-gpu
    container: registry.cern.ch/docker.io/rochaporto/gpu_burn
    steps:
      - name: nvidia-smi
        run: |
          nvidia-smi
      - name: install
        run: |
          gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys A4B469963BF863CC
          apt-get -y update
          DEBIAN_FRONTEND=noninteractive apt-get -y install cmake
      - name: configure
        run: |
          cmake -B ${{github.workspace}}/build
      - name: build
        run: |
          cmake --build ${{github.workspace}}/build
      - name: test
        run: |
          ctest --test-dir ${{github.workspace}}/build
